sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ros-contributions@amazon.com
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
    - ROS_DISTRO="lunar"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
    - ROS_DISTRO="lunar"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
    - ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
    - ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
matrix:
  allow_failures:
    - env: ROS_DISTRO="lunar"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
    - env: ROS_DISTRO="lunar"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
    - env: ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
    - env: ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="robot_ws/.rosinstall"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git robot_ws/.ros_ci
script:
  - cd robot_ws && .ros_ci/travis.sh
